# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5a657379415eccab87d0608f2cd199aae7b20877e7b17b46ded6ea4f112733ec9d12c2f281e891d731cd3716e2a73668bb6629adbc1ded85c6393c76566a4ba
  twitter_client_id: 1oI75YGdWoDhAl1KCvqA76BcI
  twitter_secret: oobWMGmYPOYpJW9Rfpo1hOTtLEsbwS60MU79zqGD8wPakJNIv7
  google_client_id: 670468628153-ddoprpgm1vang4rh2mmshg9aht7dm84m.apps.googleusercontent.com
  google_secret: ex0HbUpNI6oLgjxb7kB8gF1s
  github_client_id: a3386acee67ba657a613
  github_secret: 6413b7070656bb449a13f9c4d1ca59239ca0c870
  api_token: a47a8e54b11c4de5a4a351734c80a14a

test:
  secret_key_base: fd915f7f78228c14186b8fe692be716df50829908be5eef76cf711b8f3697f9045e7aea7782296f31bdc8d9b3849654c50a071ac8919156ef75fbf9e0c93bb2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
#Number prettifier is a Test App, for deployment will use same credential as development
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_client_id: 1oI75YGdWoDhAl1KCvqA76BcI
  twitter_secret: oobWMGmYPOYpJW9Rfpo1hOTtLEsbwS60MU79zqGD8wPakJNIv7
  google_client_id: 670468628153-ddoprpgm1vang4rh2mmshg9aht7dm84m.apps.googleusercontent.com
  google_secret: ex0HbUpNI6oLgjxb7kB8gF1s
  github_client_id: a3386acee67ba657a613
  github_secret: 6413b7070656bb449a13f9c4d1ca59239ca0c870
  api_token: a47a8e54b11c4de5a4a351734c80a14a
